CREATE DATABASE nur;
USE nur;
CREATE TABLE users(id INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, sessid VARCHAR(100) NOT NULL,ready INT(3) NOT NULL);
CREATE TABLE rooms(id INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,room VARCHAR(100) NOT NULL, phase INT(3) NOT NULL);
INSERT INTO rooms (room,phase) VALUES ('1',0);
CREATE TABLE battles (id INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,member VARCHAR(100) NOT NULL,turn INT(3) NOT NULL, get VARCHAR(100) NOT NULL,tableCard VARCHAR(1024) NOT NULL,openCard VARCHAR(100) NOT NULL,winner VARCHAR(100) NOT NULL);
CREATE TABLE spades(room1 INT(3) NOT NULL);
CREATE TABLE clovers(room1 INT(3) NOT NULL);
CREATE TABLE hearts(room1 INT(3) NOT NULL);
CREATE TABLE dias(room1 INT(3) NOT NULL);

